In [14]:
import numpy as np
matrix = np.array([[ 1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])
print(matrix)
transpose_matrix = np.transpose(matrix)
print(transpose_matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
